# Generated by Django 5.1.6 on 2025-02-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('direction', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend')], max_length=50)),
                ('languages', models.CharField(help_text='Укажите языки программирования через запятую', max_length=255)),
                ('contact_status', models.BooleanField(default=False)),
            ],
        ),
    ]
