# Generated by Django 5.1.6 on 2025-02-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_user_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.AddField(
            model_name='user',
            name='programming_language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('php', 'PHP'), ('react', 'React'), ('c++', 'C++')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend')], default='backend', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
