# Generated by Django 5.1.6 on 2025-02-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_candidate_contacted_remove_mentor_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
