# Generated by Django 5.1.6 on 2025-02-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('thinking', 'Думает'), ('contacted', 'Связались'), ('test_started', 'Пошел тест'), ('test_failed', 'Не прошел тест'), ('declined', 'Отказался')], default='thinking', max_length=20),
        ),
    ]
