# Generated by Django 5.1.6 on 2025-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_candidate_mentor_delete_user_candidate_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='contacted',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='expertise',
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('thinking', 'Думает'), ('contacted', 'Связались')], default='thinking', max_length=20),
        ),
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='direction',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Backend (Java)', 'Backend (Java)'), ('Backend (Python)', 'Backend (Python)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
