# Generated by Django 5.1.6 on 2025-02-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_candidate_is_deleted_mentor_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='is_deleted',
        ),
    ]
