# Generated by Django 5.1.6 on 2025-02-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('thinking', 'Думает'), ('contacted', 'Связались'), ('passed_test', 'Прошел тест')], default='thinking', max_length=20),
        ),
    ]
